Repository puppetlabs/puppetlabs-motd, pull requests merged in 2019-04, with the labels that each got.

#204 (MODULES-8758) Change memoryfree to memorysize in template
  README.md
  spec/classes/motd_spec.rb
  templates/motd.epp
Labels: bugfix

#205 (MODULES-8767) Add support for SLES 15
  metadata.json
Labels: feature

#208 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#200 (FM-7647) use puppet_litmus for acceptance testing
  .fixtures.yml
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  Rakefile
  appveyor.yml
  distelli-manifest.yml
  metadata.json
  provision.yaml
  spec/acceptance/locales_spec.rb
  spec/acceptance/motd_spec.rb
  spec/spec_helper_acceptance.rb
Labels: feature

#210 (maint) add more oses to test in pipelines
  provision.yaml
Labels: maintenance

#211 pdksync - (maint) Update pdk-template to f778803
  metadata.json
Labels: maintenance

#213 (maint) - More consistent ENV vars for .travis.yml
  .travis.yml
Labels: maintenance
