Repository puppetlabs/puppetlabs-motd, pull requests merged in 2019-11, with the labels that each got.

#249 (FM-8275) Add vagrant provision list
  appveyor.yml
  provision.yaml
Labels: maintenance

#259 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#262 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#263 (MODULES-10087) - Release Merge back v4.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#264 (FM-8691) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#265 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .gitlab-ci.yml
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
Labels: maintenance
