Repository puppetlabs/puppetlabs-motd, pull requests merged in 2019-05, with the labels that each got.

#215 (MODULES-9017) - update metadata to support current version of stdlib
  metadata.json
Labels: maintenance

#216 (FM-8073) litmus block support
  spec/acceptance/locales_spec.rb
Labels: bugfix

#217 (bugfix) remove scientific 5 testing
  distelli-manifest.yml
  provision.yaml
Labels: bugfix

#222 FM-8043 - redhat8 support
  metadata.json
  provision.yaml
Labels: feature

#223 (bugfix) allow private keys in ssh testing
  spec/spec_helper_acceptance.rb
Labels: bugfix

#224 (maint) remove extra spaces at EOL
  REFERENCE.md
  manifests/init.pp
Labels: maintenance

#225 (maint) exit if travis setup fails
  .travis.yml
Labels: maintenance
