Repository puppetlabs/puppetlabs-motd, pull requests merged in 2020-11, with the labels that each got.

#350 Update dependencies
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .pdkignore
  .rubocop.yml
  .sync.yml
  Gemfile
  metadata.json
Labels: dependencies, maintenance

#353 Update rspec-puppet dev version to pull from default branch
  .sync.yml
  Gemfile
  metadata.json
Labels: dependencies

#360 pdksync - Update pdk-templates for gitpod and codespaces support
  .gitpod.Dockerfile
  .gitpod.yml
  .sync.yml
  Gemfile
  data/common.yaml
  hiera.yaml
  metadata.json
Labels: maintenance

#365 pdksync - (maint) Add release_checks_7 config to provision.yaml
  provision.yaml
Labels: maintenance
