Repository puppetlabs/puppetlabs-motd, pull requests merged in 2020-01, with the labels that each got.

#276 MODULES-10387-update dependencies
  metadata.json
Labels: maintenance

#277 pdksync - (FM-8581) - Debian 10 added to travis and provision file refactored
  .sync.yml
  .travis.yml
  provision.yaml
Labels: feature

#278 (MODULES-10458) Release version v4.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#271 FreeBSD compatibility
  manifests/init.pp
Labels: bugfix
