Repository puppetlabs/puppetlabs-motd, pull requests merged in 2021-03, with the labels that each got.

#401 Update metadata.json - remove ubuntu 14.04
  metadata.json
Labels: backwards-incompatible

#404 (IAC-1497) - Removal of unsupported `translate` dependency
  .fixtures.yml
  locales/config.yaml
  locales/ja/puppetlabs-motd.po
  locales/puppetlabs-motd.pot
  manifests/init.pp
  metadata.json
Labels: bugfix

#403 pdksync - PDK Update - Replace Travis and Appveyor with Github Actions
  .github/workflows/auto_release.yml
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/spec.yml
  .pdkignore
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: maintenance
