Repository puppetlabs/puppetlabs-motd, pull requests merged in 2023-04, with the labels that each got.

#473 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#472 (Cont 787) Add Support for Puppet 8 / Drop Support for Puppet 6
  .devcontainer/devcontainer.json
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  manifests/init.pp
  metadata.json
  spec/acceptance/motd_spec.rb
  spec/classes/motd_spec.rb
  spec/spec_helper.rb
  templates/motd.epp
Labels: backwards-incompatible

#475 (CONT-860) Update registry dependency
  metadata.json
Labels: bugfix
